# Spring配置
spring:
  application:
    name: alpsFile
 
  #zipKin 指向
  zipkin:
      base-url: http://localhost:9411
      enabled: true 
  sleuth: 
      web:
        client:
          enabled: true
      sampler: 
        probability: 1.0  #zipkin采集率  0.1表示 10%采集

  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    listener:
     direct:
       retry:
        enabled: true
     simple:
       retry:
        enabled: true
  queue: zipkin
   
#注册中心指向start 
#同一服务做负载LB时ID需要不一样，否则eureka会覆盖。   
eureka:
  instance:
    instance-id: alpsFile
    appname: ${spring.application.name}
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry:  true  #是否从Eureka中获取注册信息，默认为true 
    service-url: 
      defaultZone: http://alps:alps$888@127.0.0.1:8888/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
