spring: 
  profiles: 
    include: 
        - gateway
        - druid
  
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    database: 3
    lettuce:
      pool:
        max-active: 10 
        max-idle: 8   
        max-wait: 100 
        min-idle: 2  
      shutdown-timeout: 100ms
#redis cluster config

mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


#设置最大容错超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000



#设置最大容错超时时间
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 5000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      circuitBreaker:
        forceOpen: false
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 900000
  
  

#注册中心指向start 
#同一服务做负载LB时ID需要不一样，否则eureka会覆盖。   
eureka:
  instance:
    instance-id: alps-gateway
    appname: ${spring.application.name}
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry:  true  #是否从Eureka中获取注册信息，默认为true 
    service-url: 
      defaultZone: http://alps:alps$888@127.0.0.1:8888/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
            